# Generated by Django 4.1.4 on 2023-04-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietapp', '0002_expert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cooked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('ing', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Raw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('ing', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
