# Generated by Django 4.1.4 on 2023-04-19 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietapp', '0003_cooked_raw_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooked',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='raw',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
