# Generated by Django 4.1.4 on 2023-04-19 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dietapp', '0004_cooked_link_raw_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pyramid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast', models.CharField(max_length=200)),
                ('bcal', models.CharField(max_length=200)),
                ('lcal', models.CharField(max_length=200)),
                ('dcal', models.CharField(max_length=200)),
                ('lunch', models.CharField(max_length=200)),
                ('dinner', models.CharField(max_length=200)),
                ('exp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dietapp.expert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dietapp.registration')),
            ],
        ),
    ]
