# Generated by Django 4.1.4 on 2023-04-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietapp', '0008_remove_request_link_request_bmi_request_disease_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='disease',
        ),
        migrations.AddField(
            model_name='request',
            name='breakfast',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='dinner',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='esnack',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='lunch',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='snack',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
