# Generated by Django 4.1.4 on 2023-04-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietapp', '0009_remove_request_disease_request_breakfast_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='healthstat',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
