# Generated by Django 4.1.4 on 2023-04-24 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dietapp', '0010_request_healthstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='expert',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dietapp.expert'),
        ),
    ]
