# Generated by Django 4.1.4 on 2023-04-24 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dietapp', '0011_request_expert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pyramid',
            name='exp',
        ),
        migrations.AddField(
            model_name='pyramid',
            name='req',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dietapp.request'),
        ),
    ]
